### ISSUE TITLE
How do I access the web panel?

### ISSUE THREAD

**Issue by SpaceBurn** [CYBERDEVILZ/Cryptonite#54]
How do I access the web panel? When I go to 127.0.0.1:8050 it fails to load. I tired to run CommandCenter.py but I got this error.

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Cryptonite-main\Cryptonite\CommandCenter.py", line 77, in <module>
    hovertext='<b>' + df["IP Address"] + '</b>' + '<br>' + df["Place"],
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\ops\common.py", line 69, in new_method
    return method(self, other)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\arraylike.py", line 96, in __radd__
    return self._arith_method(other, roperator.radd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\ops\array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\ops\array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\roperator.py", line 9, in radd
    return right + left
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U3'), dtype('float64')) -> None

**Comment by CYBERDEVILZ** [comment]
Hi @SpaceBurn ,
I have already addressed this issue and has even rolled out a patch for it. Please make sure that you have forked the latest version of Cryptonite.

Here is the issue: #49

**Comment by SpaceBurn** [comment]
Ok
