### ISSUE TITLE
error when executing exegen on kali   

### ISSUE THREAD

**Issue by demosecuring** [CYBERDEVILZ/Cryptonite#61]
i get this error when running the command python3 exegen.py on the terminal 

407 INFO: PyInstaller: 3.5+498e6ee058
407 INFO: Python: 3.10.6
408 INFO: Platform: Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34
409 INFO: wrote /home/kali/Cryptonite/Cryptonite/WindowsUpdate.spec
411 INFO: UPX is available.
411 INFO: Removing temporary files and cleaning cache in /home/kali/.cache/pyinstaller
411 INFO: Extending PYTHONPATH with paths
['/home/kali/Cryptonite/Cryptonite', '/home/kali/Cryptonite/Cryptonite']
411 INFO: checking Analysis
412 INFO: Building Analysis because Analysis-00.toc is non existent
412 INFO: Initializing module dependency graph...
416 INFO: Initializing module graph hooks...
417 INFO: Analyzing base_library.zip ...
8511 INFO: Processing pre-find module path hook   distutils
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/kali/Cryptonite/Cryptonite/WindowsUpdate.spec", line 6, in <module>
    a = Analysis(['Cryptonite.py'],
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 348, in assemble
    self.graph = initialize_modgraph(
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/analysis.py", line 613, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1473, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1657, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale
mv: cannot stat './dist/WindowsUpdate': No such file or directory
rm: cannot remove '__pycache__': No such file or directory

**Comment by CYBERDEVILZ** [comment]
You are running exeGen via a POSIX operating system like Linux or Mac. I highly suggest you run the program on a Windows device as pyinstaller creates **exe** files in Windows environment only.

**Comment by i6c** [comment]
> You are running exeGen via a POSIX operating system like Linux or Mac. I highly suggest you run the program on a Windows device as pyinstaller creates **exe** files in Windows environment only.

Yeah, I thought it was explicitly said so much times that it only works in windows.
